name: Desplegar Frontend Dev a Docker Hub y Servidor

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Definir nombre de imagen y versión (Dev)
        run: |
          IMAGE_NAME="baumanpeter/humberto:humbertofrontend-dev-v${{ github.run_number }}"
          echo "IMAGE_VERSION=$IMAGE_NAME" >> $GITHUB_ENV
          echo "✅ Imagen de desarrollo: $IMAGE_NAME"

      - name: Verificar contenido del directorio
        run: ls -l .

      - name: Construir imagen Docker y cargarla localmente
        run: |
          echo "🚀 Construyendo imagen Docker..."
          docker buildx build --platform linux/amd64 --no-cache --load -t $IMAGE_VERSION .
          echo "✅ Imagen construida y cargada localmente."

      - name: Subir imagen a Docker Hub
        run: |
          echo "📤 Subiendo imagen a Docker Hub..."
          docker push $IMAGE_VERSION
          echo "✅ Imagen subida correctamente."

      - name: Desplegar a Servidor Dev vía SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEV_SSH_HOST || secrets.SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USER || secrets.SSH_USER }}
          key: ${{ secrets.DEV_SSH_KEY || secrets.SSH_KEY }}
          envs: IMAGE_VERSION
          script: |
            echo "📥 Iniciando despliegue remoto en ambiente de desarrollo..."
            docker pull $IMAGE_VERSION

            cd /root/Proyecto_H/DockerComposeHumberto-dev

            echo "🔄 Actualizando imagen en docker-compose.yml..."
            sed -i "s|baumanpeter/humberto:humbertofrontend-dev-v[0-9]*|$IMAGE_VERSION|g" docker-compose.yml

            echo "🛠 Ejecutando script de actualización..."
            cd /root/Proyecto_H
            ./update_all_services.sh

            echo "🚀 Despliegue de desarrollo completado."
