name: Deploy Frontend to Docker Hub

on:
  push:
    branches:
      - master  # Ejecuta el workflow cuando hay un push a la rama "dev"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production  # Asigna el Environment llamado "production"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Define Image Tag
        env:
          IMAGE_NAME: baumanpeter/humberto:humbertofrontend
        run: |
          echo "🔢 Configurando versión de la imagen..."
          IMAGE_VERSION="${{ env.IMAGE_NAME }}-v${{ github.run_number }}"
          echo "IMAGE_VERSION=$IMAGE_VERSION" >> $GITHUB_ENV
          echo "✅ Imagen con versión: $IMAGE_VERSION"

      - name: Verify directory contents
        run: ls -l .

      - name: Build Docker image and load locally
        run: |
          echo "🚀 Construyendo la imagen Docker..."
          docker buildx build --platform linux/amd64 --load -t $IMAGE_VERSION .
          echo "✅ Imagen construida y cargada en Docker local."

      - name: List Docker images (debugging)
        run: docker images

      - name: Push Docker image to Docker Hub
        run: |
          echo "📤 Subiendo la imagen a Docker Hub..."
          docker push $IMAGE_VERSION
          echo "✅ Imagen subida exitosamente a Docker Hub."
